embedding_size: 64
n_ui_layers: 4
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-5
learning_rate: 0.001

cl_loss: 0.01 
temperature: 0.2
image_knn_k: 20
text_knn_k: 15

dropout_rate : 0.1

hyper_parameters: ["diff_beta", "diff_only_down"]

use_diffusion_mvp: true
diff_beta: [0.5]
diff_only_down: [true]

# spec_method: dwt
# dwt_keep_ratio: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]
# dwt_use_softthr: false

# spec_method: wiener
# wiener_alpha: 0.5
# wiener_eps: 1e-6

spec_method: fft

edge_nce_k: 10
edge_nce_lambda: 0
edge_use_user_pool: true
edge_user_pool_L0: 50
edge_inbatch_negs: true
edge_inbatch_ratio: 2
